version: '3.8'

services:
  cart-service:
    image: ghcr.io/bgcheong/cart-service:latest
    container_name: cart-service-container
    ports: ["8094:8084"]
    depends_on: 
      - redis
    networks:
      - service
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  service:
    external: true