version: '3.8'

services:
  user-service:
    image: ghcr.io/bgcheong/user-service:latest
    container_name: user-service-container
    init: true
    # ports: ["8092:8082"]
    restart: always
    networks:
      - service
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  service:
    external: true